# Generated by Django 5.0.6 on 2024-06-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stuMessage',
            field=models.CharField(default='NAN', max_length=50),
        ),
    ]
