# Generated by Django 5.0.6 on 2024-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuName', models.CharField(max_length=70)),
                ('stuAddress', models.CharField(max_length=70)),
                ('stuMessage', models.CharField(default='NAN', max_length=50)),
            ],
        ),
    ]
