# Generated by Django 5.0.6 on 2024-06-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopform',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
